## NumPy

In [2]:
import numpy as np

### Phase 1 (Creaing Arrays)

In [ ]:
array_1 = np.array([1, 2, 3, 4, 5, 6]) # Normal Array
zeros = np.zeros(10) # Array full of zeros
ones = np.ones(5,int) #Array Full of ones
arange_Array = np.arange(5) # Array from desired number to give limit here desired is not given so choosen 0, and liit is 5 so it will print from 0 to 5
linspace = np.linspace(0, 1, 10) # it will create an array containing 10 elements between 0 and 1 (evenly spaced)
identity = np.eye(5)# it will creare an identity matrix of desired size

print("Array1 : ", array_1)
print("Zeros Array : ", zeros)
print("Ones Array : ", ones)
print("Arange Array : ", arange_Array)
print("Linspace Array : ", linspace)
print("identity Array : \n", identity)

Array1 :  [1 2 3 4 5 6]
Zeros Array :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Ones Array :  [1 1 1 1 1]
Arange Array :  [0 1 2 3 4]
Linspace Array :  [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
identity Array : 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Array Properties