## NumPy

In [2]:
import numpy as np

### Phase 1 (Creaing Arrays)

In [ ]:
array_1 = np.array([1, 2, 3, 4, 5, 6]) # Normal Array
zeros = np.zeros(10) # Array full of zeros
ones = np.ones(5,int) #Array Full of ones
arange_Array = np.arange(5) # Array from desired number to give limit here desired is not given so choosen 0, and liit is 5 so it will print from 0 to 5
linspace = np.linspace(0, 1, 10) # it will create an array containing 10 elements between 0 and 1 (evenly spaced)
identity = np.eye(5)# it will creare an identity matrix of desired size

print("Array1 : ", array_1)
print("Zeros Array : ", zeros)
print("Ones Array : ", ones)
print("Arange Array : ", arange_Array)
print("Linspace Array : ", linspace)
print("identity Array : \n", identity)

Array1 :  [1 2 3 4 5 6]
Zeros Array :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Ones Array :  [1 1 1 1 1]
Arange Array :  [0 1 2 3 4]
Linspace Array :  [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
identity Array : 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Array Properties

In [34]:
array = np.arange(1, 10)
print("Array : ", array)

print("Shape : ", array.shape)
print("Dimension : ", array.ndim)
print("Size : ", array.size)
print("DType : ", array.dtype)
print("NBytes : ", array.nbytes)

#Type Conversion
array.astype(np.float64)
print("DType : ", array.dtype)


Array :  [1 2 3 4 5 6 7 8 9]
Shape :  (9,)
Dimension :  1
Size :  9
DType :  int32
NBytes :  36
DType :  int32


### Array Operations

In [4]:
array = np.array([1, 2, 3, 4, 5, 6])

print(array)
print(np.add(array, 3))
print(np.subtract(array, 3))
print(np.multiply(array, 2))
print(np.divide(array, 2))

[1 2 3 4 5 6]
[4 5 6 7 8 9]
[-2 -1  0  1  2  3]
[ 2  4  6  8 10 12]
[0.5 1.  1.5 2.  2.5 3. ]


## Indexing and Slicing

In [53]:
# 1-D Slicing
array_1d = np.array([1, 2, 3, 4, 5, 6] )
print("Array[1] : ", array_1d[1])
print("Array[1:4] : ", array_1d[1:4])
print("Array[-1] : ", array_1d[-1])

# 2-D Slicing
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array_2D : \n", array_2d)
print("Array[1,2]", array_2d[1, 2])
print("Array[1,2]", array_2d[:, 2])
print("Array[1,2]", array_2d[:, :])

# 3-D Slicing
array_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[11, 22, 33], [44, 55, 66], [77,88, 99]]])
print("Array_3d : \n", array_3d)
print("Array[0, 1, 2]", array_3d[0, 1, 2])



Array[1] :  2
Array[1:4] :  [2 3 4]
Array[-1] :  6
Array_2D : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array[1,2] 6
Array[1,2] [3 6 9]
Array[1,2] [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array_3d : 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]]
Array[0, 1, 2] 6


## Indexing

In [58]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("Array : ", array)

#Boolean Indexnig
print("Array elements greater than 5: ", array[array > 5])
#where clause
new_array = np.where(array > 5, array, "false")
print("Altered Array : ", new_array)
#Mask
mask = array > 3
print("Array wwith msk : ", array[mask])
indices = [1,2, 4]
print("Values for te indices : ", array[indices])

Array :  [1 2 3 4 5 6 7 8]
Array elements greater than 5:  [6 7 8]
Altered Array :  ['false' 'false' 'false' 'false' 'false' '6' '7' '8']
Array wwith msk :  [4 5 6 7 8]
Values for te indices :  [2 3 5]


### Universal unctions

In [3]:
array = np.array([1, 2, 4, 5, 6])
print(np.sqrt(array))
print(np.exp(array))
print(np.log(array))
print(np.power(array,2))

[1.         1.41421356 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   54.59815003 148.4131591  403.42879349]
[0.         0.69314718 1.38629436 1.60943791 1.79175947]
[ 1  4 16 25 36]


## Phase 2

### Reshaping

In [ ]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(array.shape)

# Now reshaping int into a 2-D Array
array_2D = array.reshape(3, 3) #beaware that the size of array should be enough to reshape it
print(array_2D)

# For instance if we have an array of 7 elements than it is not reshapable into any 2-D

newArray = array_2D.reshape(1, 9)
print(newArray)

# Automatic Dimensions
# here -1 auomatically determines wha size should the column(or row) be if i require 3 rows(or columns)
array_2 = array.reshape(3, -1)
print(array_2)
print(array.reshape(-1, 3))

(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Reizing

In [ ]:
array = np.array([1, 2, 3, 4, 5, 6])
print(array)
array.resize(3, 3)
print(array)

array2 = array.resize(3, 3) # it doesnot returns anything so array2 is null(none)
print(array2)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]
 [0 0 0]]
None


In [ ]:
array = np.random.randint(0, 9, size = (3, 3))
print("Original Array")
print(array)

print("Flatten Array")
flatten = array.flatten()
print(flatten)
flatten[0] = 100
print(array)

print("Ravel Array")
ravelarray = array.ravel()
print(ravelarray)
ravelarray[0] = 100
print(array)

print("reshape Array")
reshape = array.reshape(-1)
print(reshape)
reshape[0] = 101
print(array)

# ravel() => it changes the original array(because it shares same memory with the original array)
# flatten() => it doesnot changes the original array(because it not shares same memory with the original array)
# reshape(-1) => it changes the original array(because it shares same memory with the original array)

Original Array
[[1 8 0]
 [2 5 4]
 [7 8 2]]
Flatten Array
[1 8 0 2 5 4 7 8 2]
[[1 8 0]
 [2 5 4]
 [7 8 2]]
Ravel Array
[1 8 0 2 5 4 7 8 2]
[[100   8   0]
 [  2   5   4]
 [  7   8   2]]
reshape Array
[100   8   0   2   5   4   7   8   2]
[[101   8   0]
 [  2   5   4]
 [  7   8   2]]
